import type { CSSProperties } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Inter_Tight } from "next/font/google";
import { WhatsAppFloatingButton } from "@prime2b/ui-kit/primitives/WhatsAppFloatingButton";
import { mockPrimeLocal } from "./mock/prime-local.mock";
import "./globals.css";

/**
 * Overrides the CSS variables @prime2b/ui-kit/tokens.css defines at
 * :root, scoped to <body> so mockPrimeLocal.cores is what actually
 * renders — those tokens.css values are only ui-kit's own dev
 * fallback, not live data, so without this override every section
 * would silently render the fallback navy instead of this mock's
 * palette regardless of what mockPrimeLocal.cores says.
 */
const themeVars = {
  "--color-primary": mockPrimeLocal.cores.primary,
  "--color-secondary": mockPrimeLocal.cores.secondary,
  "--color-text": mockPrimeLocal.cores.text,
  "--color-accent": mockPrimeLocal.cores.accent,
} as CSSProperties;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Distinct variable names, redirected to the --font-title/--font-body
// design tokens in globals.css's @theme block (same pattern as
// --font-geist-sans below) — avoids colliding with the literal
// fallback values @prime2b/ui-kit/tokens.css sets on --font-title/body.
const interBody = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const interTightTitle = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${interBody.variable} ${interTightTitle.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" style={themeVars}>
        {children}
        <WhatsAppFloatingButton
          whatsapp={mockPrimeLocal.whatsapp}
          nome={mockPrimeLocal.nome}
          mensagemPrincipalWhatsapp={mockPrimeLocal.mensagemPrincipalWhatsapp}
        />
      </body>
    </html>
  );
}
